# Generated by Django 5.2 on 2025-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('taskTime', models.DurationField()),
                ('breakTime', models.DurationField()),
            ],
        ),
    ]
